# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

new_height = np.array([69,70,71,72,73,74,75])
new_weight = np.array ([110,120,130,140,150,160,170])

result_bmi = new_weight / (new_height ** 2) * 730
result_bmi

array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [30]:
import numpy as np
import ast

def random_matrix():
    minimum = int(input("What would you like the minimum number of the matrix to be? "))
    maximum = int(input("What would you like the maximum number of the matrix to be? "))
    matrix = input("What would you like the size of the Matrix to be? Ex.(3,3) ")
    
    matrix = ast.literal_eval(matrix)
    
    print(f'Here is a {str(matrix)} matrix with numbers between {minimum} and {maximum}: \n %s' % np.random.uniform(minimum, maximum, matrix))
   
random_matrix()
    


What would you like the minimum number of the matrix to be? 1
What would you like the maximum number of the matrix to be? 5
What would you like the size of the Matrix to be? Ex.(3,3) (4,4)
Here is a (4, 4) matrix with numbers between 1 and 5: 
 [[4.87641945 1.57461087 2.92285225 4.72952829]
 [3.52384574 1.34555722 1.84945069 1.1667988 ]
 [4.94976072 3.79425636 3.77299313 4.95709082]
 [3.68023622 3.44443422 2.77283405 1.94855689]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [43]:
import csv
import numpy as np




In [62]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../numpy/redsox_2017_hitting.txt')
bs2018 = load_data('../numpy/redsox_2018_hitting.txt')

slugging_18 = bs2018['SLG']

slugging_17 = bs2017['SLG']


new_slugging_18 = np.array([slugging_18]).sum()
new_slugging_17 = np.array([slugging_17]).sum()

len_slugging_17 = np.array([slugging_17]).shape[1]
len_slugging_18 = np.array([slugging_18]).shape[1]

div_slugging_17 = new_slugging_17 / len_slugging_17
div_slugging_18 = new_slugging_18 / len_slugging_18


if div_slugging_18 > div_slugging_17:
    print("The 2018 Boston Red Soxs had a better Slugging Percentage than the 2017 Boston Red Soxs")
else:
    print("The 2017 Boston Red Soxs had a better Slugging Percentage than the 2018 Boston Red Soxs")






The 2017 Boston Red Soxs had a better Slugging Percentage than the 2018 Boston Red Soxs
